name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Cheermate.sln

      - name: Build
        run: dotnet build Cheermate.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Cheermate.sln --configuration Release --no-build --logger trx
