name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore Cheermate.sln

      - name: Build (Non-Windows projects)
        run: |
          dotnet build Cheermate.Domain/Cheermate.Domain.csproj --configuration Release --no-restore
          dotnet build Cheermate.Application/Cheermate.Application.csproj --configuration Release --no-restore
          dotnet build Cheermate.Infrastructure/Cheermate.Infrastructure.csproj --configuration Release --no-restore
          dotnet build Cheermate.Tests/Cheermate.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test Cheermate.Tests/Cheermate.Tests.csproj --configuration Release --no-build --logger trx

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore Cheermate.sln

      - name: Build
        run: dotnet build Cheermate.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Cheermate.sln --configuration Release --no-build --logger trx
